In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('train_loan.csv')

categorical_cols = ['Gender', 'Married', 'Dependents', 'Self_Employed']
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)


numerical_cols = ['LoanAmount', 'Loan_Amount_Term', 'Credit_History']
for col in numerical_cols:
    df[col].fillna(df[col].median(), inplace=True)


missing_values = df.isnull().sum()
missing_values[missing_values > 0]

<ipython-input-10-d1b10e8254b1>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
<ipython-input-10-d1b10e8254b1>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

Series([], dtype: int64)

In [7]:
import numpy as np

def cap_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return np.clip(series, lower, upper)

df['ApplicantIncome'] = cap_outliers(df['ApplicantIncome'])
df['LoanAmount'] = cap_outliers(df['LoanAmount'])

In [8]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding
le = LabelEncoder()
df['Loan_Status'] = le.fit_transform(df['Loan_Status'])  # Y -> 1, N -> 0

# Convert 'Dependents' to numeric, replacing '3+' with 3
df['Dependents'] = df['Dependents'].replace('3+', 3).astype(int)

# One-Hot Encoding for remaining categorical variables
df_encoded = pd.get_dummies(df.drop(columns=['Loan_ID']), drop_first=True)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])